### ISSUE TITLE
auto closes

### ISSUE THREAD

**Issue by alvingzy** [Art3mLapa/PG-Sn1per#2]
Traceback (most recent call last):
  File "D:\Users\Michelle\Downloads\PG-Sn1per-main\PG-Sn1per-main\main.py", line 264, in <module>
    generate_and_check_links()
  File "D:\Users\Michelle\Downloads\PG-Sn1per-main\PG-Sn1per-main\main.py", line 145, in generate_and_check_links
    config = json.load(config_file)
  File "C:\Users\Michelle\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Michelle\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Michelle\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Michelle\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 140 (char 141)

**Comment by Art3mLapa** [comment]
Try reinstalling the code and installing the libraries again.

**Comment by alvingzy** [comment]
{
   "webhook": "https://discord.com/api/webhooks/.z", // ur webhook
   "account_age (2005-2016)": 2008, // account age
   "ItemID": "1567446", // ID item or bundle that accounts must have
   "follower_limit": 100 // follower limit - the fewer followers, the greater the chances of a successful PG
}

**Comment by alvingzy** [comment]
never mind, turns out there was something wrong with the config file, i use chatGPT to solve it lol
