### ISSUE TITLE
what do i do this?

### ISSUE THREAD

**Issue by alvingzy** [Art3mLapa/PG-Sn1per#3]
Traceback (most recent call last):
  File "/home/runner/PG-Sn1per/main.py", line 264, in <module>
    generate_and_check_links()
  File "/home/runner/PG-Sn1per/main.py", line 145, in generate_and_check_links
    config = json.load(config_file)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 140 (char 141)

**Comment by Art3mLapa** [comment]
Good Morning!
I already wrote about this. an error in the wrong config or due to a library not downloaded.
The following entries will be ignored, since I have already given the answer. There can be no error due to the code itself
